<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Arkanis.External.MedRunner.Models\Arkanis.External.MedRunner.Models.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6"/>
    </ItemGroup>

</Project>
